#!/usr/bin/env python3
"""Re-read every artifact, run every claim assertion, and write provenance/numbers.json
and provenance/CLAIM_PROVENANCE.md. Fails if any claim is not supported by the artifacts."""
import json, hashlib
from _common import ROOT, load
M = load("build_research_note_v0.py")               # import-time asserts on every claim
L = load("build_research_note_latex_v0.py")         # V13 / blind-4 / resolution asserts + main.tex
A = ROOT / "artifacts"
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()[:16]
v13 = json.loads((A / "cde_v13_blind_out/unblinding_report.json").read_text()); b4 = json.loads((A / "cde_blind4_out/scoring.json").read_text())
st1 = json.loads((A / "cde_risoluzione_claim_out/esito_stage1.json").read_text())["esito"]; bl = json.loads((A / "cde_v8_pysindy_baseline_v0_out/results.json").read_text())
jl = json.loads((ROOT / "baselines/julia/scoring.json").read_text())["esito"]
claims = [
  {"claim": "exact support on 5 PDEs, 0-10% noise, seeds 7 and 11; max coefficient error", "value": f"{100*M.max_true_err:.2f}%", "artifact": "cde_pde_discovery_v8_out/*/results.json, cde_ks_discovery_v9_out/*/results.json", "code": "CDE_PDE_DISCOVERY_V8.py, CDE_KS_DISCOVERY_V9.py", "campaign": "V8 / V9 (protocol v1.1)", "builder": "build_research_note_v0.py (asserts)", "where": "abstract, Results"},
  {"claim": "0 false discoveries in null controls", "value": f"0 / {M.n_null_total}", "artifact": "results.json nulls sections", "code": "CDE_PDE_DISCOVERY_V8.py", "campaign": "V8 / V9 / external solver", "builder": "build_research_note_v0.py", "where": "abstract, Results, Conclusion"},
  {"claim": "PySINDy null false discoveries, vanilla vs + epistemic gate", "value": f"{M.bl_null_fd}/{M.bl_null_runs} -> {M.bl_fd_gated}/{M.bl_null_runs}", "artifact": "cde_v8_pysindy_baseline_v0_out/results.json", "code": "baseline runner (PySINDy 2.1.0) + gate transplant", "campaign": "paired baseline", "builder": "build_note_figures_v0.py fig_gate_null", "where": "Results 6.4, Fig. 3b"},
  {"claim": "V13 sealed replica: false claims / opportunities", "value": f"{v13['domanda_A']['n_claim_false']} / {v13['domanda_A']['opportunita']} ({100*v13['domanda_A']['n_claim_false']/v13['domanda_A']['opportunita']:.1f}%)", "artifact": "cde_v13_blind_out/unblinding_report.json", "code": "CDE_V13_BLIND_DISCOVERER_V0.py + CDE_V13_BLIND_UNBLINDING_V0.py", "campaign": "V13 replica (prereg 2026-08-02)", "builder": "build_research_note_latex_v0.py (asserts)", "where": "abstract, Section 8.1"},
  {"claim": "V13: false claims on nulls / on non-representable", "value": f"0/{v13['domanda_A']['nulli']} and 0/{v13['domanda_A']['non_rappresentabili']}", "artifact": "cde_v13_blind_out/unblinding_report.json", "code": "CDE_V13_BLIND_UNBLINDING_V0.py", "campaign": "V13 replica", "builder": "build_research_note_latex_v0.py", "where": "Section 8.1"},
  {"claim": "V13: Mac/Windows agreement on shared cases", "value": f"{v13['domanda_B']['n_condivisi']}/{v13['domanda_B']['n_condivisi']}", "artifact": "cde_v13_blind_out/verdicts_{mac,win}.json", "code": "CDE_V13_BLIND_UNBLINDING_V0.py domanda_B", "campaign": "V13 replica", "builder": "build_research_note_latex_v0.py", "where": "Section 8.1"},
  {"claim": "resolution bound, diagnostic: violations at k=1 / k=2", "value": f"{st1['per_k']['1.0']['n_violazioni']} / {st1['per_k']['2.0']['n_violazioni']} on {st1['n']} claims", "artifact": "cde_risoluzione_claim_out/esito_stage1.json", "code": "CDE_RISOLUZIONE_CLAIM_V0.py, CDE_RISOLUZIONE_ANALYZER_V0.py", "campaign": "Stage 1 (prereg 2026-09-03)", "builder": "build_research_note_latex_v0.py", "where": "Section 8.2, Fig. 4a"},
  {"claim": "independent implementation (Julia) on the same design matrices: nulls claimed / with the gate / most generous policy", "value": f"{jl['nulli_rivendicati']}/{jl['nulli']} / {jl['nulli_rivendicati_gated']}/{jl['nulli']} / {jl['nulli_rivendicati_oracolo']}/{jl['nulli']}", "artifact": "baselines/julia/{risultati_dde.json,scoring.json}, artifacts/cde_feature_export_out/", "code": "CDE_ESPORTA_FEATURE_V0.py + run_dde.jl + CDE_BASELINE_JULIA_SCORER_V0.py", "campaign": "paired independent baseline (prereg 2026-09-07)", "builder": "build_research_note_latex_v0.py (asserts)", "where": "Results 6.4"},
  {"claim": "independent implementation: exact support on true cells, ours vs PySINDy's features", "value": f"{jl['supporto_esatto']}/{jl['vere']} vs 14/20", "artifact": "baselines/julia/scoring.json, cde_v8_pysindy_baseline_v0_out/results.json", "code": "run_dde.jl + CDE_BASELINE_JULIA_SCORER_V0.py", "campaign": "paired independent baseline", "builder": "build_research_note_latex_v0.py", "where": "Results 6.4"},
  {"claim": "blind-4: claims / sub-support / violations / verdict", "value": f"{b4['esito']['n_claim']} / {b4['esito']['sotto_supporto']} / {len(b4['esito']['violazioni'])} / {b4['esito']['verdetto']}", "artifact": "cde_blind4_out/scoring.json, claim_dettaglio.json", "code": "CDE_BLIND4_RUNNER_V0.py + CDE_BLIND4_SCORER_V0.py", "campaign": "blind-4 (prereg 2026-09-03, truth sha in envelope)", "builder": "build_research_note_latex_v0.py, build_note_figures_v0.py fig_resolution", "where": "Section 8.2, Fig. 4b"},
]
out = {"numbers": claims, "artifact_sha256_16": {**{"baselines/julia/scoring.json": sha(ROOT / "baselines/julia/scoring.json")}, **{k: sha(A / k) for k in ("cde_v13_blind_out/unblinding_report.json", "cde_blind4_out/scoring.json", "cde_risoluzione_claim_out/esito_stage1.json", "cde_v8_pysindy_baseline_v0_out/results.json")}}}
(ROOT / "provenance/numbers.json").write_text(json.dumps(out, indent=1))
rows = "\n".join(f"| {c['claim']} | **{c['value']}** | `{c['artifact']}` | `{c['code']}` | {c['campaign']} | {c['builder']} | {c['where']} |" for c in claims)
(ROOT / "provenance/CLAIM_PROVENANCE.md").write_text("# Claim provenance\n\nGenerated by `builders/build_numbers.py` from the committed artifacts; every row is asserted at build time and the build aborts if an artifact disagrees.\n\n| paper claim | value | artifact | code | campaign | builder | where in paper |\n|---|---|---|---|---|---|---|\n" + rows + "\n")
print(f"{len(claims)} claims verified -> provenance/numbers.json, CLAIM_PROVENANCE.md")
